### ISSUE TITLE
"Add profile stats and gallery links after each user" have stopped working.

### ISSUE THREAD

**Issue by capoaira** [magma1447/greasemonkey-geocaching-projectgc#104]
https://project-gc.com/qa/?qa=27548/user-script-profile-stats-gallery-links-after-stopped-working

I can reproduce this issue

**Comment by rteitelman** [comment]
Is this still broken in the lastest version?  2.3.14   If I look at logs and click on a user who logged it, it DOES take me to their stats page on geocaching.com and that stats page also includes a link to their gallery.  So maybe this got fixed after this issue was submitted almost a year ago?

**Comment by magma1447** [comment]
From what I can see this works now. Either it has been fixed and we forgot to close the issue, or it wasn't broken, or HQ made changes that made it work again. :)

Closing.
