### ISSUE TITLE
Add latest logs

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#109]
The Add latest logs feature has stopped working.

**Comment by rteitelman** [comment]
Well I looked at the code and don't have any idea why it's not working.  Line 1101:
             // Show latest logs
            // Enhanced Nov 2016 to show icons for up to 5 of the latest logs
            if (IsSettingEnabled('addLatestLogs') && latestLogs.length <= 5) {
                var images = latestLogs.join('');

**Comment by jewettg** [comment]
I have found a fix!  If I could be added as a contributor, I will create a branch, and submit pull request with my change.  It is minor for this one; but there are other fixes that I would like to help with! :)

**Comment by rteitelman** [comment]
magma1447.....  my buddy jewettg found the problem with the script I reported April 25.  I tested and it works.  Can you make him a Contributor to Github?  PS - His Geocaching name is GeoJewett.    He's also looking at something else with the script.

**Comment by magma1447** [comment]
> @magma1447 - I worked with @rteitelman and we have found a fix! If I could be added as a contributor, I will create a branch, and submit pull request with my change. It is minor for this one; but there are other fixes that I would like to help with! :)

The easiest is to fork the repository here on GitHub. Submit a fix there, and then make a pull request. When the pull request is accepted (manual process by me) the one making the pull will automatically be added as a contributor. I am not an expert, but in case you don't find your way around GitHub I will try to help.

**Comment by jewettg** [comment]
@magma1447  - Thanks.  So, GitHub is part of my life at work.  While, I probably do not use it to its full advantage, we have setup or repos with approval on pull requests and merges of branches, never really forks, but you learn something new everyday.  So yeah I will give it a shot.  @rteitelman has quite a list of things for me to fix! So hopefully I can be helpful!

**Comment by jewettg** [comment]
@magma1447 - Pull request has been made.  Moving on to other changes @rteitelman needs fixed.

**Comment by jewettg** [comment]
@magma1447  - I would be more than happy to help you manage the repo, do code checks, merge pull requests, etc..   Yes, the code has lots of potential and lots of re-writing that could happen.   I have @rteitelman who can do testing for me, as well as myself.  I am sure there are others in my community that could help test as well.  I can send them test code before I submit a pull-request.

I read through a bunch of the issues, and I am sure I can tackle at least half of them pretty quickly.  I am more than happy to help as a member of the Geocaching community.

**Comment by rteitelman** [comment]
My Issue #2 - Not working - If the last log is a DNF, Display Blue Warning at Top of the page.

**Comment by rteitelman** [comment]
My Issue #3 - The line right before the logs begin has a logs summary that looks like this:
  View all logs (9) | Yours (1) | Friends' | View Gallery (1)      
NOTE: Above line is for my view of GC9VGC

that value of Yours is wrong, I have 2 logs not 1.  Friends' has no value.  It should be 1.  Godot is my friend with 1 log.  I think that single ' is a typo ?

**Comment by magma1447** [comment]
@jewettg I will look into adding you so that you get more control of the code and repository during the day. It's a bit out of my comfort zone though. Not that you become a maintainer, but the technical/ui-part of it. :)

A few thoughts:
1. Try to keep one patch per commit please.
2. Whenever you bump the version number there will automatically be a new release. The version number follows the Linux standards (x.y.z). X is for major changes, either breaking or really big changes. Y is for new features in general, and Y can be greater than 9 (ie 1.45.3 is valid). Z is for release version, typically set to 0, or bumped upon bug fixes or really minor changes that no one would miss.
3. Always feel free to ask me things. If you are a Discord user you can find me more accessible at ht tps://dis  cord.g  g/5mV 8f  
 p78rz (remove all spaces). There I am more responsive than via GitHub.
4. Feel free to add yourself as maintainer in the README after you have made a few relevant patches. Acknowledgement to contributors should exist whenever deserved of course.

**Comment by jewettg** [comment]
@magma1447  -- I appreciate the olive branch! :)  I promise with all the channels of communication (here, email, Discord, etc..) that I will reach out with any questions.  All the versioning methods are exactly what we use at work.  I work for the University of Texas at Austin.  I am an automation engineer.. developing in Python, Bash, PowerShell, PHP, Perl, etc.. to help my fellow IT colleagues and sysadmins minimize the manual tasks they have to perform.  Github is part of my life, so I am happy to give you some insight in DevOps, version control, and environment code lifecycle.

We might consider a developer branch, aka "nightly" release .. that can be rolled into production after testing by the community.  People can test out fixes, features, etc.. and let us know if they work, need tweaking, etc..  This would of course not mess with the prod version or its versioning, unless we a promoting.  Versioning usually very custom to whatever we want.   v1.45.3(a|d|b)xxx, where xxx can be numeric, or alpha numeric, whatever.

As for the one patch per commit, yes.  For back tracking, it is important to be able to roll back.  That is the beauty of version control and utilizing environment branches.

I have also started work on the WIKI, as that is also one of my passions.. good documentation.   So I will be working on both aspects, the WIKI documentation and the comments and docs within code.
