### ISSUE TITLE
Count of Friends logs not displaying on the log summary line showing count of: All Logs, Yours, Friends, Gallery #115

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#116]
There is no number showing after 'Friends'.  All Logs, and Yours have numbers, but not Friends.

**Comment by rteitelman** [comment]
I think we can close this case also.  I don't believe that this script ever displayed the count of your friends logs on this log summary line.  If you just click on the link, you'll see that count number and the logs.  So its no big deal if it's not displayed until you click on the link for Friends logs.

**Comment by magma1447** [comment]
I believe it's correct to say that it was never displayed. This because Project-GC doesn't know about which friends one has, as it is today. When building this it wasn't possible. Today it's technical possible, but it still doesn't collect the data.
