### ISSUE TITLE
Misleading wording on PGC script options menu

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#117]
Option 4: ADD PGC MAP LINKS should say ADD LINK TO PGC LIVE MAP

**Comment by magma1447** [comment]
If the end result isn't too long, in a way that it ruins the UI, I would prefer if it says PROJECT-GC instead of PGC.

**Comment by rteitelman** [comment]
Fixed in version 2.3.17 along with a few other small wording changes on the settings menu.
