### ISSUE TITLE
ADD LINKS TO PROFILE STATS can be removed from the PGC script settings menu

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#118]
as far as I can tell,  this does nothing.  perhaps magma1447 knows?

**Comment by magma1447** [comment]
After every _profile name_ in the logbook it should add a small image (typical link image) which is a link to https://project-gc.com/ProfileStats/<profile-name>. The blue icon after Herman... in the attached screenshot.

![Screenshot_2022-08-24_22-18-21](https://user-images.githubusercontent.com/1918311/186515466-1f8ac06c-f8d8-496b-903e-374859c50e3f.png)

**Comment by rteitelman** [comment]
I see now where the link is placed.   Closing Issue.
