### ISSUE TITLE
ADD LINKS TO PGC GALLERY settings option can be removed

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#119]
This appears to be another setting that currently does nothing.

**Comment by magma1447** [comment]
Similar to my answer in #118. Adds a gallery-icon-link for each name in the logbook. The "photo" icon in the attached screenshot, after the name Herman...

![Screenshot_2022-08-24_22-18-21](https://user-images.githubusercontent.com/1918311/186515720-339f7c3a-20aa-401a-92bc-e4544d1f0817.png)
.

**Comment by rteitelman** [comment]
I see now where the link is placed.   Closing Issue.
