### ISSUE TITLE
ADD LINKS FOR BOOKMARK LISTS Settings option can be removed

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#120]
I see no place this has any effect.

**Comment by magma1447** [comment]
It does do something. On a geocache page there are two widgets on the right side if the geocache exists in bookmark lists. This setting adds a few icons with links for each entry. See screenshot.

![Screenshot_2022-08-24_22-27-32](https://user-images.githubusercontent.com/1918311/186516805-042106f6-186d-44d5-b63a-e2bbe18b3dc3.png)

**Comment by rteitelman** [comment]
Closed. I see now the two small links added to each Bookmark List that this setting affects.
