### ISSUE TITLE
MY NUMBER OF LOGS above Log Button

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#121]
This is a script option to enable/disable.   In any event, it's returning an incorrect value in some cases.   Example for me:  GC9VGCC  I have two logs (one find, one DNF).   But the page says:  You have 1 logs according to Project-GC

**Comment by magma1447** [comment]
This is a backend bug in the API. This is something I will have to fix.

**Comment by magma1447** [comment]
Issue found. It happens when the number of found logs is the same as the number of logs that aren't Found (or photo taken and equivalents). I will close this one since it will work with the next release of the server side code (might be a few days).
