### ISSUE TITLE
Warning Line that Last Log is a DNF is still not working

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#122]
In yesterday's release 2.3.15, the blue warning line when the last log is a DNF, is still not working.   Guess this new line still has an issue:
if ($('#cache_logs_table span.h4 img').attr('src') === '/images/logtypes/3.png') {

**Comment by rteitelman** [comment]
well, it sorta works.   Here it is, but it takes a VERY LONG time for that blue warning line to appear.   Like MANY minutes.   Why?

![Screenshot 2022-08-24 133034](https://user-images.githubusercontent.com/67875917/186558886-fbf43fc3-0130-415b-9b2a-b33d1d1691b1.jpg)

**Comment by magma1447** [comment]
It is working. Any delays are caused by your client. As soon as the html has finished loading the relevant JS code will be executed, on the client (web browser). Nothing in the code causes any delays.

All my tests have been instant, more or less. At least < 0.5 seconds.
