### ISSUE TITLE
Setting to Compose Log entries in Drafts in same window.  Is this still needed?

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#124]
I have no idea what this means.  I thought Draft log entries only pertained to the Geocaching app.  Not the website.

**Comment by magma1447** [comment]
Drafts exists on the web as well. The drafts are created by apps, then converted into logs via the website.
https://www.geocaching.com/account/drafts

It does seem like the code isn't needed anymore though. From my tests it looks like HQ changed their web to not open in new windows all the time.

**Comment by rteitelman** [comment]
Looks like we don't need to worry about this code anymore.
