### ISSUE TITLE
Settings menu reloads page if GClh is installed

### ISSUE THREAD

**Issue by capoaira** [magma1447/greasemonkey-geocaching-projectgc#140]
>Ok, found the Issue: With the GClh it does not work. Without, this issue is fixed. I'll open a new issue, and maybe I find some time next week to take a look into it.

_Originally posted by @capoaira in https://github.com/magma1447/greasemonkey-geocaching-projectgc/issues/108#issuecomment-1237153282_

**Comment by cghove** [comment]
e.preventDefault(); to line 473 should fix it (not tested just a guess)
![Screenshot_20220905-164938_Chrome](https://user-images.githubusercontent.com/26240443/188475522-7ac10b60-1510-4f9b-b282-9ae377e5fa63.jpg)

**Comment by capoaira** [comment]
Make sense 😅👍🏻
Tested and it works 👍🏻
