### ISSUE TITLE
Include new features from GC little helper ?

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#144]
does anyone think perhaps that some of the more useful featues of gclh should be incorporated into this, so that only one script is necessary for those currently running both?  Since I am retired and have time, I'd be willing to attempt to try working on this.  any thoughts anyone?  Somebody in one of the closed tickets mention that some of the features in gclh were very useful.

On another note, shouldn't someone check on all the old issues (magma1447?) and see if they can be closed out?

**Comment by capoaira** [comment]
I see no need for it. This Script is, as the name says, for the connection between geocaching.com and PGC.
The GCLH change/add/remove many, many things, and I don't think you want to migrate over 17000 lines of code. The GClh is always in development, so it would be difficult to keep it up to date in another script.

I try to keep an eye on all user scripts to solve issues if tow of them are in conflict. It wouldn't be helpful if this script also include GClh features.

**Comment by rteitelman** [comment]
got it, thannks for that.  17,000 lines of code, sheesh.
