### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by capoaira** [magma1447/greasemonkey-geocaching-projectgc#156]
When clock on "Not logged in" in the header, then on "Authenticate" and "Zustimmen" (Agree), the browser shows me plain text
```txt
string(921) "<a-long-string-i-thing-my-auth-key>"
string(100) "https://api.groundspeak.com/v1.0/users/PRBXJEK?fields=membershipLevelId%2ChomeCoordinates%2Cusername"
Internal server error (65ba7325d6e5a6.60069675)
```
But I'm not logged in :-(

**Comment by magma1447** [comment]
This is unrelated to the userscript, but the issue itself was fixed yesterday. It's an aftereffect from changes that Geocaching HQ has made.
