### ISSUE TITLE
Change the map links

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#30]
The script links PGC maps using Map Compare. The link exists on top right on cache pages. It should instead link the new Live map.

This will require coordinate conversion in JS, or some changes server side. If the coordinates doesn't already exist as decimal form on the geocache page. Handling it client side is the best, they will probably be useful for linking Google maps as well (https://greasyfork.org/en/forum/discussion/6179/x).

**Comment by magma1447** [comment]
If implemented without server side support a reward of a 1 year membership coupon code will be sent to the one who makes a working pull request.

Add a note here with your gc name to claim the reward.

**Comment by pkubiak** [comment]
It seems that this task has already been resolved in 655b308fe6efef652ccd907b9b6fb3842fd0dea4

**Comment by magma1447** [comment]
Oh, funny that I have fixed that one myself and forgotten about it. I'll merge that one later today. Thanks.

**Comment by magma1447** [comment]
Apparantly fixed in 655b308, and merged.
