### ISSUE TITLE
Show warning when geocache is locked

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#31]
The locked flag exists in the API and Project-GC provides it. Add a very visible div on the geocache page when the geocache is in fact locked. Something that Geocaching.com doesn't show at all? At least I can't find it at http://coord.info/GC65551 .

**Comment by magma1447** [comment]
This warning should probably be added as a paragraph after the archived warning. I imagine bold red text (same red as the archived warning). Other ideas are welcome.

I do not see any need for a setting to toggle this function.

I imagine this issue to be a quite easy fix. The data is already returned from PGC with the GetCacheData method. The item is named "locked" and is either a 0 or a 1.

**Comment by GeekNJ** [comment]
Was going to look at attempting this item but I don't see "locked" as being returned in GetCacheDataFromGccode.  I see a few fields in the response but not "locked".

**Comment by magma1447** [comment]
My fault, I thought we returned more data. I made a oneliner patch from my smartphone. Either the item exists now, or I have broken it. Can't test GreaseMonkey in my phone...

**Comment by magma1447** [comment]
I will update the api method to return a boolean instead. Patch live in two minutes.

**Comment by GeekNJ** [comment]
Made straightforward change and submitted request. Message to be added: 
This cache is locked and can no longer be logged.

Can be tested with https://www.geocaching.com/geocache/GC2725_radio-k-a-o-s which is a locationless cache.

**Comment by magma1447** [comment]
Fixed by 73e7089

**Comment by magma1447** [comment]
Didn't test it earlier, just reviewed the code, it was about 5 am back then.

Now I have tested it as well. Looks awesome. I didn't really remember how the HTML looked, but there really was a natural way to inject the HTML.
