### ISSUE TITLE
DNF warning

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#38]
If the last log is a DNF, make a clearer warning about this.

My design skills are close to none existing, I imagine a text string where the archived text usually is, in a slightly larger blue font saying "Warning, last log is a Did not Find.", blue because the DNF icon is blue. I imagine blue being more visible than red at Geocaching.com.

A six month membership coupon code will be rewarded to the one closing this issue. Add you gc name in a note to claim the reward.

**Comment by Surfoo** [comment]
![tmp](https://cloud.githubusercontent.com/assets/553659/20727889/7e16d0bc-b67b-11e6-8699-2bad3196b07e.jpg)
What do you think? :)

**Comment by Surfoo** [comment]
My geocaching username is the same of github, but you already know it :)

**Comment by magma1447** [comment]
I think it looks amazing. I know I will appreciate this one myself. And yes, I know your name, but it was a good reminder, you now have a PM at Project-GC.

Thanks!
