### ISSUE TITLE
Project-GC user menu not visible everywhere

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#42]
The Project-GC user menu isn't visible everywhere.
* https://www.geocaching.com/ redirects to https://www.geocaching.com/play/search nowadays, it's not working there.
* Neither does it work at https://www.geocaching.com/play/hide
* Or https://www.geocaching.com/play/geotours

The fix is most likely the same/similar for those. The first one is most important though.

**Comment by magma1447** [comment]
I will send a coupon code granting 1 year of membership at Project-GC to whomever solves the user menu at the above pages as well.

**Comment by sdahlbac** [comment]
I'll have a look, will report back either way.
