### ISSUE TITLE
Req: link back to profile from msg center

### ISSUE THREAD

**Issue by frold** [magma1447/greasemonkey-geocaching-projectgc#57]
In the message center I would like to have an easy link back to the profile I'm chatting with
![skaermbillede 2017-02-16 kl 23 00 34](https://cloud.githubusercontent.com/assets/25831117/23043401/6ddf8f18-f49c-11e6-8b1d-c0af1e0820f0.png)

With a mouse over function or something

Is that possible?

Im new to github, so I hope I do it right :)

**Comment by Jakuje** [comment]
You can visit the profile of the user who writes you by clicking on the profile icon next to his message. Having this somehow more user friendly would be certainly nice.

**Comment by frold** [comment]
yeah, I know - but that feature is only availble if the users have answered you.

But it might being the wrong place to ask for this enhancement.

**Comment by Surfoo** [comment]
It seems not really easy to add a link on the picture, there is a click event listener on '<li class="selected>' and if we disable it, we can't read messages...

**Comment by frold** [comment]
Okay, it's not that important either.
