### ISSUE TITLE
PGC User menu can't be opened on Settings-page

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#66]
The PGC user menu is broken at https://www.geocaching.com/account/settings/preferences .

It seems to me like $('#pgcUserMenu, #pgcSettingsOverlay').toggle() doesn't match anything, even though both elements exists.

**Comment by sdahlbac** [comment]
The problem seems to be that there is no jquery available. I'll see if I can come up with a fix.
