### ISSUE TITLE
The GPS Maze events miss "Will attend logs per country" part

### ISSUE THREAD

**Issue by Jakuje** [magma1447/greasemonkey-geocaching-projectgc#69]
to my understanding, this part needs to be send by server side and there is nothing to fix in the extension itself (it just prints what it gets from the server). You can reproduce this bug with the recent MAZE:

http://coord.info/GC6GB1C

**Comment by Jakuje** [comment]
If I see right, MAZE is not considered as an event by PGC (does not get listed in EventStatistcs):

https://project-gc.com/Tools/EventStatistics?gccode=GC6GB1C

**Comment by magma1447** [comment]
We had some reference to what Geocaching.com called event, which we adjusted our data for. I can however not find that reference. The best I can find right now is https://www.geocaching.com/help/index.php?pg=kb.chapter&id=23&pgid=48 and that doesn't seem very complete.

I will change our development environment to include all cache types that uses the *Attended* log type. The list is as follows:

- Event Cache
- Mega-Event Cache
- Lost and Found Event Cache
- Cache In Trash Out Event
- Groundspeak Lost and Found Celebration
- GPS Adventures Exhibit
- Groundspeak Block Party
- Giga-Event Cache

It should go live with the next release.

**Comment by Jakuje** [comment]
Thanks. It should do that. GPS Maze is officially retired by Groundspeak in US, but it does not apply for Europe. For the record, this short KB article talks about it:
https://www.geocaching.com/help/index.php?pg=kb.chapter&id=12&pgid=603

**Comment by magma1447** [comment]
Hans who does Project-GC's support remembered the other reference.
It's in our statistics at Geocaching.com, the group "All event cache types". Example: https://www.geocaching.com/p/default.aspx?guid=29830521-10ff-47db-9b9d-4d84826eb3ae&tab=geocaches#profilepanel

That's my profile, I haven't logged all kinds of "events" though, but Maze I have logged, and it was excluded. I might personally think that it's more reasonable to use all cache types with Attended logs though.

When going through a few other profiles one can find the difference. It's *GPS Adventures Exhibit* and the one-time *Groundspeak Lost and Found Celebration*. In a way I can agree with the first not being counted as an event. There isn't any social aspect, it's an exhibit. The later I have no personal experience from.
