### ISSUE TITLE
Greasemonkey v4 incompatible

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#73]
Greasemonkey for Firefox has been rewritten "from scratch".
Source: https://www.ghacks.net/2017/09/21/greasemonkey-4-firefox-57-compatibility/

The new version doesn't work with this userscript. The reason might be found in:
https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

**Comment by Lineflyer** [comment]
I noticed the same while checking out Greasemonkey V4 after upgrading Firefox to V57.
However as I also noticed incompatabilities of Greasemonkey V4 with several other scripts I am using I changed to Tampermonkey which seems to perform well with the PGC script (and all others).

**Comment by magma1447** [comment]
@Lineflyer I am not an expert, but I believe TamperMonkey will get issues with Firefox as well. This is due to the fact that they are dropping their old plugin-engine.

Anyway, Jakuje has made a working fix for this userscript at least, seems to be working fine, will merge it soon.

**Comment by Jakuje** [comment]
AFAIK Tampermonkey somehow implements the transition layer and compatibility with the old Greasemonkey (or other systems) so even the old script works usually as expected, but I am not following it closely.

Greasemonkey on the other hand stepped away to somehow new API and new functions, which should eventually get better performance with the new Firefox API and added a external script for compatibility with old GM versions (it can be dropped some time later as there will be no users using that).
